### ISSUE TITLE
Is index swapping on the HiSeq 4000 a problem?

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/SpikeIns2016#1]
All but the first plate by Fernando were generated on a HiSeq 4000. If index swapping occurred at a high rate, this would homogenize all libraries and distort the variance estimates. We have several ways to check the extent of swapping in the different data sets.

__Calero:__ The first four rows of the plate were control cells while the last four rows were cells induced to express the _CBFB-MYH11_ oncogene. In theory, the control cells should not express the oncogene, but the regulation is leaky. Some expression is therefore expected, and cannot be used directly as evidence of index swapping. Fortunately, the first plate was generated on the 2500 while the second plate was generated on the 4000. If we compute the _CBFB-MYH11_ log-fold changes between induced and control groups, we get values of 4.6 for the first plate and 6.7 for the second plate. There is no decrease in the log-fold change for the second plate, which would be indicative of homogenization due to index swapping.

__Liora:__ Both plates contained one empty well (no cell, only spike-in transcripts). If swapping were a problem, this well would contain non-negligible amounts of mouse transcript. Examination of the data indicate that the counts for the empty well are several orders of magnitude below that of the other mouse cells (649 vs 1386765 for the first plate, 3253 vs 1394308 for the second plate). This suggests that any swapping that might be present is negligible and can be ignored.

**Comment by jcmarioni** [comment]
Good! :)
John

---

John Marioni PhD
Research Group Leader, EMBL-EBI
Associate Faculty Member, WT Sanger Institute
Wellcome Genome Campus
CB10 1SD, UK

Senior Group Leader
CRUK Cambridge Institute
University of Cambridge
CB2 0RE, UK

**Comment by LTLA** [comment]
I think we can avoid needing to resequence these libraries, so I'm closing this issue.

**P.S.** There are also some other mitigating factors that I should mention:

- Index swapping is most problematic when a library with, say, a highly expressed gene bleeds over into a library with no expression of that gene. This results in a large fold-increase in the apparent expression, which can be quite misleading, e.g., for marker genes. However, this is not a problem here as all wells should contain comparable levels of spike-in transcript. This reduces the relative increase in observed expression and the potential for incorrect conclusions.
- Swapping is also problematic when there are both small and large libraries on the same plate. Even though the percentage loss from the large library might be minor, the percentage gain in the small library could be quite substantial. In our case, all libraries lie within an order of magnitude in terms of their spike-in counts. This indicates that a 1% swapping rate (it's probably lower, but I'll be conservative) from the largest library will only result in a 10% increase in the spike-in counts in the smallest library. This is an acceptable worst case given that most libraries are closer in size.
